[default]
src = 'contracts'
out = 'out'
test = 'test'
verbosity = 3
libs = ["node_modules", "lib"]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/=node_modules/@rari-capital/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
